# Generated by Django 5.0.6 on 2024-07-19 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.CharField(default='2M1', max_length=3, primary_key=True, serialize=False)),
                ('dia', models.IntegerField(choices=[(0, 'Domingo'), (1, 'Segunda'), (2, 'Terça'), (3, 'Quarta'), (4, 'Quinta'), (5, 'Sexta'), (6, 'Sábado')], default=True)),
                ('horaInicio', models.TimeField(blank=True, null=True)),
                ('horaFim', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoLocal',
            fields=[
                ('tipo', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoRecurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('tipo', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('bloco', models.CharField(max_length=10)),
                ('capacidade', models.IntegerField()),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_SIGApoio.tipolocal')),
            ],
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id_codigo', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('codigo', models.IntegerField(blank=True)),
                ('status', models.BooleanField(blank=True, choices=[(True, 'Disponível'), (False, 'Indispovível')], default=True)),
                ('funcionando', models.BooleanField(blank=True, choices=[(True, 'Sim'), (False, 'Não')], default=True)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_SIGApoio.tiporecurso')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('matricula', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('tipo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_SIGApoio.tipousuario')),
            ],
        ),
    ]
