# Generated by Django 5.0.6 on 2024-07-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservamensal',
            name='horaFim',
            field=models.TimeField(default='22:00'),
        ),
        migrations.AddField(
            model_name='reservamensal',
            name='horaInicio',
            field=models.TimeField(default='07:00'),
        ),
        migrations.AddField(
            model_name='reservamensal',
            name='mesInicial',
            field=models.IntegerField(choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')], default=7),
        ),
    ]
