# Generated by Django 5.0.6 on 2024-07-22 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_reserva_reservasemanal_reservadiaunico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservadiaunico',
            name='descricao',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reservamensal',
            name='descricao',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reservasemanal',
            name='descricao',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
