# Generated by Django 5.0.6 on 2024-08-06 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_reservamensal_horafim_reservamensal_horainicio_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReservaMensal',
        ),
    ]
