# Generated by Django 5.0.6 on 2024-07-22 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_reservadiaunico_descricao_reservamensal_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservadiaunico',
            name='diaHoraInicio',
            field=models.DateTimeField(),
        ),
    ]
