# Generated by Django 5.0.6 on 2024-08-18 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_reservamensal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaRecurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
                ('horaInicio', models.TimeField()),
                ('horaFim', models.TimeField()),
                ('docente', models.ForeignKey(limit_choices_to={'tipo__tipo': 'Docente'}, on_delete=django.db.models.deletion.CASCADE, to='app.usuario')),
                ('idRecurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.recurso')),
            ],
        ),
    ]
