# Generated by Django 5.0.6 on 2024-08-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_tipolocal_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='nome',
            field=models.CharField(max_length=50),
        ),
    ]
