# Generated by Django 5.0.6 on 2024-08-19 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_reservarecurso'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservarecurso',
            name='devolvido',
            field=models.BooleanField(default=False),
        ),
    ]
