# Generated by Django 5.0.6 on 2024-08-21 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_reservarecurso_devolvido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservarecurso',
            name='devolvido',
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='devolvido',
            field=models.BooleanField(default=False),
        ),
    ]
