# Generated by Django 5.0.6 on 2024-08-21 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_local_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='reservado',
            field=models.BooleanField(default=False),
        ),
    ]
