# Generated by Django 5.0.6 on 2024-08-26 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_user_date_joined'),
        ('app', '0006_local_reservado'),
        ('app', '0006_remove_reservarecurso_devolvido_emprestimo_devolvido'),
    ]

    operations = [
    ]
