# Generated by Django 5.0.4 on 2024-04-04 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_SIGApoio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('horaSaida', models.DateTimeField()),
                ('horaEntrada', models.DateTimeField()),
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('idRecurso', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_SIGApoio.recurso')),
            ],
        ),
    ]
