# Generated by Django 5.0.6 on 2024-07-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_SIGApoio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='id',
            field=models.CharField(default='2M1', max_length=3, primary_key=True, serialize=False),
        ),
    ]
