# Generated by Django 5.0.3 on 2024-06-27 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_SIGApoio', '0002_emprestimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='id_codigo',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
