# Generated by Django 5.0.4 on 2024-04-04 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_SIGApoio', '0002_emprestimo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Emprestimo',
        ),
    ]
