# Generated by Django 5.0.3 on 2024-07-05 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_SIGApoio', '0003_alter_recurso_id_codigo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Emprestimo',
        ),
    ]
