# Generated by Django 5.0.4 on 2024-04-04 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_SIGApoio', '0003_delete_emprestimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_SIGApoio.tipousuario'),
        ),
    ]
