# Generated by Django 5.0.3 on 2024-07-05 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_SIGApoio', '0004_delete_emprestimo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horaSaida', models.DateTimeField(auto_now=True)),
                ('horaEntrada', models.DateTimeField(blank=True, null=True)),
                ('idRecurso', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_SIGApoio.recurso')),
                ('matBolsista', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_SIGApoio.usuario')),
                ('matUsuario', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_usuario', to='app_SIGApoio.usuario')),
            ],
        ),
    ]
