# Generated by Django 5.0.4 on 2024-04-05 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_SIGApoio', '0005_emprestimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='matUsuario',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_usuario', to='app_SIGApoio.usuario'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
