# Generated by Django 5.0.4 on 2024-04-05 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_SIGApoio', '0006_emprestimo_matusuario_alter_emprestimo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='matUsuario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_usuario', to='app_SIGApoio.usuario'),
        ),
    ]
