# Generated by Django 5.0.4 on 2024-04-05 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_SIGApoio', '0007_alter_emprestimo_matusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='matBolsista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_SIGApoio.usuario'),
        ),
    ]
