# Generated by Django 5.0.4 on 2024-04-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_SIGApoio', '0010_alter_emprestimo_horaentrada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='horaEntrada',
            field=models.DateTimeField(),
        ),
    ]
