# Generated by Django 5.0.4 on 2024-04-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_SIGApoio', '0011_alter_emprestimo_horaentrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='horaSaida',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
