# Generated by Django 5.0.4 on 2024-04-08 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_SIGApoio', '0016_emprestimo_ma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codHorario', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='horaEntrada',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
