# Generated by Django 5.0.4 on 2024-04-08 23:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_SIGApoio', '0017_horario_alter_emprestimo_horaentrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='ma',
            field=models.TimeField(blank=True, null=True, verbose_name=datetime.datetime(2024, 4, 8, 23, 15, 55, 814569)),
        ),
    ]
