# Generated by Django 5.0.4 on 2024-04-08 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_SIGApoio', '0018_alter_emprestimo_ma'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='dia',
            field=models.IntegerField(blank=True, choices=[(0, 'Domingo'), (1, 'Segunda'), (2, 'Terça'), (3, 'Quarta'), (4, 'Quinta'), (5, 'Sexta'), (6, 'Sábado')], default=True),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='ma',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
