# Generated by Django 5.0.3 on 2024-04-09 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_SIGApoio', '0021_alter_horario_dia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('bloco', models.CharField(max_length=10)),
                ('capacidade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TipoLocal',
            fields=[
                ('tipo', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Sala',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='codHorario',
        ),
        migrations.AddField(
            model_name='reserva',
            name='horarios',
            field=models.ManyToManyField(to='app_SIGApoio.horario'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_SIGApoio.local'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='matResponsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_SIGApoio.usuario'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='matSolicitante',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_usuario', to='app_SIGApoio.usuario'),
        ),
        migrations.AddField(
            model_name='local',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_SIGApoio.tipolocal'),
        ),
    ]
