# Generated by Django 5.0.6 on 2024-07-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_SIGApoio', '0022_local_reserva_tipolocal_delete_sala_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='local',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='local',
            name='capacidade',
        ),
        migrations.AddField(
            model_name='local',
            name='local',
            field=models.CharField(choices=[('sala', 'Sala'), ('auditorio', 'Auditório'), ('laboratorio', 'Laboratório')], default='sala', max_length=20),
        ),
        migrations.AddField(
            model_name='local',
            name='numero',
            field=models.CharField(default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='local',
            name='bloco',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1),
        ),
        migrations.DeleteModel(
            name='TipoLocal',
        ),
    ]
